version = 0.1

[default.deploy.parameters]
stack_name = "tender-agent"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
resolve_image_repos = true
s3_bucket = "oaks-sam"
s3_prefix = "tender-agent"
confirm_changeset = true
